// <auto-generated />
namespace ExpenseManager_WafaM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210226_stillgoing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210226_stillgoing));
        
        string IMigrationMetadata.Id
        {
            get { return "202102270325301_20210226_stillgoing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
