// <auto-generated />
namespace ExpenseManager_WafaM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Wafam_20210218_1408 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wafam_20210218_1408));
        
        string IMigrationMetadata.Id
        {
            get { return "202102181909516_Wafam_20210218_1408"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
