// <auto-generated />
namespace ExpenseManager_WafaM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Wafam_20210219_1630 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wafam_20210219_1630));
        
        string IMigrationMetadata.Id
        {
            get { return "202102192130323_Wafam_20210219_1630"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
